name: Build
on:
  push:

jobs:
  test-plugin:
    name: "Plugin: Build"
    runs-on: ubuntu-latest
    steps:
      - name: Env variables
        run: |
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> $GITHUB_ENV
          echo "TWILIO_API_KEY=${{ secrets.TWILIO_API_KEY }}" >> $GITHUB_ENV
          echo "TWILIO_API_SECRET=${{ secrets.TWILIO_API_SECRET }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Twilio
        run: npm install twilio-cli -g && twilio plugins:install @twilio-labs/plugin-flex

      - name: NPM dependencies
        run: npm ci

      - name: Build plugin
        run: |
          twilio flex:plugins:build
